### ISSUE TITLE
Special Stage Restart Bug

### ISSUE THREAD

**Issue by PimpUigi** [Rubberduckycooly/Sonic-CD-11-Decompilation#109]
https://www.dropbox.com/s/fo2how1ubjsssbb/SpecialStageRestartCrash.mkv?dl=0 
When editing the Special Stage Pause Menu to expose the Restart function, we get this result.

There is no crash on the Steam version of the game.

**Comment by Jackobo-Chocobo** [comment]
The issue is caused by an incomplete data initialisation when you restart during the **same** Special Stage level.
So to avoid this issue, I added a new condition that test if we are on a Special Stage Level. PimpUigi had tested the modification on Windows x64, I tested for me on Linux (Lubuntu 20.04). 

Pull request is available here : https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/pull/110
