### ISSUE TITLE
[Request] Add support for videos from mobile version

### ISSUE THREAD

**Issue by sedme0** [Rubberduckycooly/Sonic-CD-11-Decompilation#32]
While the PC version uses ogv files (theora for video and vorbis for audio), the mobile version uses mp4 (h264 for video and aac for audio). The video files from the mobile version are higher quality too. At the moment, it's technically possible to use them if you re-encode them, but it's difficult to avoid generational loss while maintaining a low file size. I understand if this isn't a priority for the project, but I thought I should bring it up in case it was an oversight of some sort.

**Comment by Rubberduckycooly** [comment]
this is something we *may* look into in the future, though due to how hard getting mp4s running with the current setup is, I can't say for sure that we're ever going to get the chance to properly impliment it, though if someone creates a PR for it we'd likely accept. For now the best thing to do is to re-encode sadly

**Comment by ObiDriftKenobi** [comment]
One solution could perhaps be to just open the user's preferred video player (be it windows media player, VLC player, GNOME videos...) and pause the game until it's closed (if pausing is possible). This is something the iOS version does - it opens the system's video player.

**Comment by PookaMustard** [comment]
I wouldn't mind having a script to reencode to OGV for now. Either way, 1+ for mobile video support.

**Comment by nor2101** [comment]
If anyone cares, I converted the mobile videos to .ogv with dual audio tracks. It has been a nightmare, because the audio was clicking like crazy after the conversion with ffmpeg; I had to use ffmpeg2theora to convert and oggz-merge to create the multitrack files. The work fine and sound perfect in the decompilation now, I also tried them in the Steam version of Sonic CD but there are still clicks during playback there, and I have no clue as to why. I took the liberty to put the music with sung lyrics in the japanese tracks and fixing the quality of the us ones, also adding the good ending and bad ending sounds at the end (missing from the mobile mp4 for some reason)

**Comment by PookaMustard** [comment]
> If anyone cares, I can share the converted mobile videos to .ogv with dual audio tracks. It has been a nightmare to convert them, because the audio was clicking like crazy after the conversion with ffmpeg; I had to use ffmpeg2theora to convert and oggz-merge to create the multitrack files. They work fine and sound perfect in the decompilation now, I also tried them in the Steam version of Sonic CD but there are still clicks during playback there, and I have no clue as to why. I took the liberty to put the music with sung lyrics in the japanese tracks and fixing the quality of the us ones, also adding the good ending and bad ending sounds at the end (missing from the mobile mp4s for some reason)

Oh, I'd like these. As well as the modified video files for mobile, so I can port them to my mobile versions as well.

**Comment by nor2101** [comment]
> 
> 
> > If anyone cares, I can share the converted mobile videos to .ogv with dual audio tracks. It has been a nightmare to convert them, because the audio was clicking like crazy after the conversion with ffmpeg; I had to use ffmpeg2theora to convert and oggz-merge to create the multitrack files. They work fine and sound perfect in the decompilation now, I also tried them in the Steam version of Sonic CD but there are still clicks during playback there, and I have no clue as to why. I took the liberty to put the music with sung lyrics in the japanese tracks and fixing the quality of the us ones, also adding the good ending and bad ending sounds at the end (missing from the mobile mp4s for some reason)
> 
> Oh, I'd like these. As well as the modified video files for mobile, so I can port them to my mobile versions as well.

Here they are: https://drive.google.com/file/d/163WLHNza2bysDeQVwDwWfOrWXmAaSDqA/view?usp=sharing

I also changed the resolution from 640x480 to 854x480 with pillar boxes to compensate for the horizontal stretch that the game does. I didn't modify the original mobile mp4 videos though, the ogv files are all I have...

P.S: @Rubberduckycooly If sharing the link here is not ok I'll remove it immediately

**Comment by ColouMods** [comment]
Since downloading the cutscenes is a bit of a grey area legally, I wrote a little Batch script to automatically convert the mobile MP4 cutscenes to the PC version OGV ones with FFmpeg. It merges the audio channels and everything together so it _should_ be functionally identical to the PC version's. All you need to do is put the BAT file and the MP4 files in the same folder as `ffmpeg.exe` and it should take care of everything.

The converted cutscenes work fine aside from some minor audio stutters here and there, and I'm honestly not sure why those happen. It doesn't happen when I play the files in VLC Media Player so I guess it's a problem with the game's video player (which, judging from what I've read online, isn't the most robust). I don't know if there's a way to mitigate it, but if there is I'd appreciate if someone told me.

Here's the BAT file (in a ZIP since GitHub only allows specific format uploads): [convert.zip](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/files/5893105/convert.zip)

**Comment by nor2101** [comment]
> 
> 
> Since downloading the cutscenes is a bit of a grey area legally, I wrote a little Batch script to automatically convert the mobile MP4 cutscenes to the PC version OGV ones with FFmpeg. It merges the audio channels and everything together so it _should_ be functionally identical to the PC version's. All you need to do is put the BAT file and the MP4 files in the same folder as `ffmpeg.exe` and it should take care of everything.
> 
> The converted cutscenes work fine aside from some minor audio stutters here and there, and I'm honestly not sure why those happen. It doesn't happen when I play the files in VLC Media Player so I guess it's a problem with the game's video player (which, judging from what I've read online, isn't the most robust). I don't know if there's a way to mitigate it, but if there is I'd appreciate if someone told me.
> 
> Here's the BAT file (in a ZIP since GitHub only allows specific format uploads): [convert.zip](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/files/5893105/convert.zip)

The audio stutters were the main reason why I switched to ffmpeg2theora 0.28, which despite being old is the only tool that would make decent .ogv files; even version 0.30 had some bugs that made it unusable for me.

**Comment by Adamillo** [comment]
Hmm I wonder if it's possible to use the audio player code from Sonic 1/Sonic 2 since those two remaster came out later. Did those audio players even get updated? Can it fix the audio stutters?

**Comment by Leonx254** [comment]
In the end it was decided that mp4 support would be too much work for what it's worth
